captcha:
    key-long: 6
    img-width: 240
    img-height: 80
    open-captcha: 0
    open-captcha-timeout: 3600
cors:
    mode: strict-whitelist
    whitelist:
        - allow-origin: example1.com
          allow-methods: POST, GET
          allow-headers: Content-Type,AccessToken,X-CSRF-Token, Authorization, Token,X-Token,X-User-Id
          expose-headers: Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers, Content-Type
          allow-credentials: true
        - allow-origin: example2.com
          allow-methods: GET, POST
          allow-headers: content-type
          expose-headers: Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers, Content-Type
          allow-credentials: true
db-list:
    - disable: true
      type: ""
      alias-name: ""
      path: ""
      port: ""
      config: ""
      db-name: ""
      username: ""
      password: ""
      prefix: ""
      singular: false
      engine: ""
      max-idle-conns: 10
      max-open-conns: 100
      log-mode: ""
      log-zap: false
email:
    to: xxx@qq.com
    port: 465
    from: xxx@163.com
    host: smtp.163.com
    is-ssl: true
    secret: xxx
    nickname: test
excel:
    dir: ./resource/excel/
jwt:
    signing-key: c7fe1c44-0655-4a6f-a17c-a7daa8b2178a
    expires-time: 7d
    buffer-time: 1d
    issuer: qmPlus
local:
    path: uploads/file
    store-path: uploads/file
mysql:
    path: 127.0.0.1
    port: "3306"
    config: charset=utf8mb4&parseTime=True&loc=Local
    db-name: go-api
    username: root
    password: "123456"
    prefix: ""
    singular: true
    engine: ""
    max-idle-conns: 10
    max-open-conns: 100
    log-mode: error
    log-zap: false
redis:
    db: 0
    addr: 127.0.0.1:6379
    password: "123456"
system:
    env: public
    addr: 8888
    db-type: mysql
    oss-type: local
    use-multipoint: false
    use-redis: false
    iplimit-count: 15000
    iplimit-time: 3600
    router-prefix: ""
    app-name: "go-api"
timer:
    start: true
    spec: '@daily'
    with_seconds: false
    detail:
        - tableName: sys_operation_records
          compareField: created_at
          interval: 2160h
        - tableName: jwt_blacklists
          compareField: created_at
          interval: 168h
zap:
    level: info
    prefix: 'gva'
    format: json
    director: log
    encode-level: LowercaseLevelEncoder
    stacktrace-key: stacktrace
    max-age: 0
    show-line: true
    log-in-console: true
